# Generated by Django 5.2.7 on 2025-10-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kind',
            field=models.CharField(choices=[('CAIXA', 'Caixa'), ('ECONOMIA', 'Economia')], default='CAIXA', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='tag_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
